version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=aac_innovation
      - DB_USER=aac_user
      - DB_PASS=aac_password
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html/backend
      - uploads:/var/www/html/uploads
    networks:
      - aac-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=aac_innovation
      - MYSQL_USER=aac_user
      - MYSQL_PASSWORD=aac_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - aac-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=aac_user
      - PMA_PASSWORD=aac_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - aac-network

volumes:
  db_data:
  uploads:

networks:
  aac-network:
    driver: bridge